### ISSUE TITLE
horsengel-roulette/locales/en/common.json: Unexpected end of JSON input

### ISSUE THREAD

**Issue by SurgicalCrow** [Helmasaur/Horsengel-roulette#38]
```
3|m | SyntaxError: /root/mustafa/node_modules/horsengel-roulette/locales/en/common.json: Unexpected end of JSON input
3|m |     at parse (<anonymous>)
3|m |     at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22)
3|m |     at Module.load (internal/modules/cjs/loader.js:863:32)
3|m |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
3|m |     at Module.require (internal/modules/cjs/loader.js:887:19)
3|m |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
3|m |     at require (internal/modules/cjs/helpers.js:74:18)
3|m |     at new HorsengelRoulette (/root/mustafa/node_modules/horsengel-roulette/index.js:24:19)
3|m |     at BankCommand.run (/root/mustafa/commands/minigames/roulette.js:32:16)
3|m |     at Message.run (/root/mustafa/node_modules/discord.js-commando/src/extensions/message.js:222:34)
3|m |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
3|m |     at async CommandDispatcher.handleMessage (/root/mustafa/node_modules/discord.js-commando/src/dispatcher.js:144:19)
```

This is the error i get while starting the game

my code:

```
 const prefix = msg.guild.commandPrefix

    const hr = new HorsengelRoulette(msg, msg.member, opponent, '!', 'en');
		hr.load(6, 1); // Chamber size and number of bullets
		hr.start();
```

**Comment by Helmasaur** [comment]
Before trying anything more, may I know what version of discord.js are you using? (It's written in the package.json file of your project.)

**Comment by Helmasaur** [comment]
I found where the issue comes from and I will soon update the package. For the moment, whatever the language you choose, the strings will be in English. So you can just switch `'en'` to `'fr'`.

If you are using discord.js v12, there might be an other error. Do not hesitate to open a new ticket and I will tell you what to do. The update which will fix this issue will also fix possible compatibility issues with discord.js v12.
